// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"log/slog"

	"github.com/gofiber/fiber/v2"
	"github.com/loopopen/t-ddd-fiber-gorm/cmd/api/config"
	"github.com/loopopen/t-ddd-fiber-gorm/internal/adapters/http"
	"github.com/loopopen/t-ddd-fiber-gorm/internal/adapters/outbound/pubs"
	"github.com/loopopen/t-ddd-fiber-gorm/internal/applic/service"
	"github.com/loopopen/t-ddd-fiber-gorm/internal/infra/conf"
	"github.com/loopopen/t-ddd-fiber-gorm/internal/infra/gorm"
	"github.com/loopopen/t-ddd-fiber-gorm/internal/infra/gorm/repoimpl"
	"github.com/lopolopen/gap/broker/xkafka"

	_ "github.com/loopopen/t-ddd-fiber-gorm/docs"

	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, e *config.Env, c *config.Config, g config.Gap, k xkafka.Options, orm conf.ORM, log *slog.Logger) (*fiber.App, error) {
	db := gorm.NewGormDB(orm)
	v := pubs.NewPub(ctx, g, k, db, log)
	userRepo := repoimpl.NewUserRepo(log, db)
	userSvc := service.NewUserSvc(log, db, v, userRepo)
	app := http.NewApp(e, c, userSvc, v, log)
	return app, nil
}
